title: "OE28RubyCarShop"
email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
user:
  name_length: 50
  email_length: 255
  password_length: 6
  address: 255
  phone_number: 10
post:
  name_length: 255
  content_length: 1000
car:
  price: true
  greater_than: 0
  less_than: 100000
check_box: 1
default_image: "tst-image-1-200x216.jpg"
page: 2
image_uploader_width: 400
image_uploader_height: 300
image_size: 500
accepted_type_image: "image/gif, image/jpg, image/jpeg, image/png"
first_price: " tỷ "
second_price: " triệu"
second_price_limit: 1000
second_price_count: 3
sub_zero: /^0+/, ""
date_time_format: "%F %T"
image_size_admin: 120
home_limit: 6
page_ad: 10
